//USER
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

//USERS
export const USER_MODIFIED = 'USER_MODIFIED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

//REQUESTS
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS';
export const CREATE_REQUEST_FAILURE = 'CREATE_REQUEST_SUCCESS';
export const GET_REQUESTS = 'GET_REQUESTS';
export const VIEW_REQUESTS = 'VIEW_REQUESTS'
export const SET_REQUEST_TO_CHANGE = 'SET_REQUEST_TO_CHANGE';
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS'

//COMMENTS
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const GET_COMMENTS = 'GET_COMMENTS';
